import { expect } from 'chai';
import { ethers } from 'hardhat';
import type { Contract, Signer } from 'ethers';

const types={Event:[['actorId','bytes32'],['action','uint8'],['modelRef','bytes32'],['parentEventIds','bytes32[]'],['inputSha256','bytes32[]'],['outputSha256','bytes32'],['outputPixelSha256','bytes32'],['outputPHash','uint64'],['paramsHash','bytes32'],['privateRoot','bytes32'],['claimedAt','uint64'],['nonce','bytes32']].map(([name,type])=>({name,type}))};
const wt={Witness:[{name:'eventHash',type:'bytes32'},{name:'kind',type:'uint8'},{name:'evidenceHash',type:'bytes32'}]};
const h=(s:string)=>ethers.id(s);
const id=h('actor');const org=h('org');const zero=ethers.ZeroHash;
async function setup(){const[admin,actor,witness,attacker,sybil]=await ethers.getSigners();const c=await ethers.deployContract('ModelLedgerRegistry',[admin.address]);await c.waitForDeployment();const domain={name:'ModelLedger',version:'1',chainId:(await ethers.provider.getNetwork()).chainId,verifyingContract:await c.getAddress()};await c.connect(actor).getFunction('registerActor')(id,org,zero);const e={actorId:id,action:1,modelRef:zero,parentEventIds:[],inputSha256:[],outputSha256:h('output'),outputPixelSha256:h('pixels'),outputPHash:0,paramsHash:zero,privateRoot:zero,claimedAt:1,nonce:h('nonce')};return{c,admin,actor,witness,attacker,sybil,domain,e};}

describe('ModelLedgerRegistry',function(){
 it('registers self-asserted actors, approves, anchors and publishes issuer',async()=>{const{c,actor,e,domain,admin}=await setup();expect((await c.getFunction('getActor')(id)).status).eq(1);await c.getFunction('approveActor')(id);expect((await c.getFunction('getActor')(id)).status).eq(2);const sig=await actor.signTypedData(domain,types,e);const hash=ethers.TypedDataEncoder.hash(domain,types,e);expect(await c.getFunction('hashEvent')(e)).eq(hash);await expect(c.getFunction('anchorEvent')(e,sig)).emit(c,'EventAnchored').withArgs(hash,id,e.outputSha256);expect((await c.getFunction('getAnchor')(hash)).blockTime).gt(0);expect(await c.getFunction('firstClaim')(e.outputSha256)).eq(hash);await expect(c.getFunction('anchorEvent')(e,sig)).revertedWith('DUPLICATE_EVENT');await c.getFunction('setIssuer')(admin.address);expect(await c.getFunction('issuer')()).eq(admin.address);});
 it('enforces actor ownership and administrative role paths',async()=>{const{c,attacker}=await setup();await expect(c.connect(attacker).getFunction('approveActor')(id)).revertedWithCustomError(c,'AccessControlUnauthorizedAccount');await expect(c.connect(attacker).getFunction('revokeActor')(id,1)).revertedWithCustomError(c,'AccessControlUnauthorizedAccount');await expect(c.connect(attacker).getFunction('approveWitness')(attacker.address,h('w'))).revertedWithCustomError(c,'AccessControlUnauthorizedAccount');await expect(c.connect(attacker).getFunction('revokeWitness')(attacker.address)).revertedWithCustomError(c,'AccessControlUnauthorizedAccount');await expect(c.connect(attacker).getFunction('setIssuer')(attacker.address)).revertedWithCustomError(c,'AccessControlUnauthorizedAccount');await expect(c.connect(attacker).getFunction('anchorBatch')(h('root'),1,'ipfs://root')).revertedWithCustomError(c,'AccessControlUnauthorizedAccount');await expect(c.getFunction('registerActor')(id,org,zero)).revertedWith('ACTOR_EXISTS');await expect(c.getFunction('registerActor')(zero,org,zero)).revertedWith('EMPTY_ID');await expect(c.getFunction('approveActor')(h('missing'))).revertedWith('NOT_SELF_REGISTERED');});
 it('rejects impersonation, field changes and replay across chain and contract',async()=>{const{c,actor,attacker,e,domain,admin}=await setup();await expect(c.getFunction('anchorEvent')(e,await attacker.signTypedData(domain,types,e))).revertedWith('SIGNER_MISMATCH');const sig=await actor.signTypedData(domain,types,e);await expect(c.getFunction('anchorEvent')({...e,modelRef:h('changed')},sig)).revertedWith('SIGNER_MISMATCH');await expect(c.getFunction('anchorEvent')(e,await actor.signTypedData({...domain,chainId:1},types,e))).revertedWith('SIGNER_MISMATCH');const other=await ethers.deployContract('ModelLedgerRegistry',[admin.address]);await other.connect(actor).getFunction('registerActor')(id,org,zero);await expect(other.getFunction('anchorEvent')(e,sig)).revertedWith('SIGNER_MISMATCH');});
 it('rejects malformed event shapes, zero output and future timestamps',async()=>{const{c,actor,e,domain}=await setup();for(const[change,error]of [[{action:14},'INVALID_ACTION'],[{parentEventIds:[h('p')]},'PARENT_ALIGNMENT'],[{outputSha256:zero},'INVALID_EVENT'],[{claimedAt:2**48},'INVALID_EVENT']]as const){const p={...e,...change};await expect(c.getFunction('anchorEvent')(p,await actor.signTypedData(domain,types,p))).revertedWith(error);}});
 it('retains anchors before revocation and forbids new ones',async()=>{const{c,actor,e,domain}=await setup();await c.getFunction('approveActor')(id);await c.getFunction('anchorEvent')(e,await actor.signTypedData(domain,types,e));const eid=await c.getFunction('hashEvent')(e);const anchor=await c.getFunction('getAnchor')(eid);await c.getFunction('revokeActor')(id,anchor.blockTime);expect((await c.getFunction('getAnchor')(eid)).blockTime).eq(anchor.blockTime);expect((await c.getFunction('getActor')(id)).revokedFrom).eq(anchor.blockTime);await expect(c.getFunction('anchorEvent')(e,await actor.signTypedData(domain,types,e))).revertedWith('ACTOR_UNAVAILABLE');await expect(c.getFunction('revokeActor')(id,anchor.blockTime)).revertedWith('CANNOT_RELAX_REVOCATION');await expect(c.getFunction('revokeActor')(h('unknown'),1)).revertedWith('UNKNOWN_ACTOR');await expect(c.getFunction('revokeActor')(id,0)).revertedWith('INVALID_REVOCATION_TIME');});
 it('requires approved independent witnesses, deduplicates organizations and retains evidence hash',async()=>{const{c,actor,witness,sybil,domain,e}=await setup();await c.getFunction('anchorEvent')(e,await actor.signTypedData(domain,types,e));const eid=await c.getFunction('hashEvent')(e);const message={eventHash:eid,kind:1,evidenceHash:h('evidence')};const sign=async(w:Signer)=>w.signTypedData(domain,wt,message);await expect(c.getFunction('witness')(eid,1,message.evidenceHash,await sign(witness))).revertedWith('WITNESS_UNAPPROVED');await c.getFunction('approveWitness')(witness.address,h('independent'));await c.getFunction('approveWitness')(sybil.address,h('independent'));await c.getFunction('witness')(eid,1,message.evidenceHash,await sign(witness));expect(await c.getFunction('witnessCount')(eid)).eq(1);expect(await c.getFunction('witnessedBy')(eid,h('independent'))).eq(true);expect((await c.getFunction('getWitnesses')(eid))[0].evidenceHash).eq(message.evidenceHash);await expect(c.getFunction('witness')(eid,1,message.evidenceHash,await sign(sybil))).revertedWith('DUPLICATE_ORG');await c.getFunction('revokeWitness')(witness.address);expect((await c.getFunction('witnesses')(witness.address)).approved).eq(false);await expect(c.getFunction('approveWitness')(witness.address,h('other'))).revertedWith('IMMUTABLE_ORG');});
 it('rejects same-org and unknown-event witnesses',async()=>{const{c,actor,witness,domain,e}=await setup();await c.getFunction('anchorEvent')(e,await actor.signTypedData(domain,types,e));const eid=await c.getFunction('hashEvent')(e);await c.getFunction('approveWitness')(witness.address,org);const message={eventHash:eid,kind:1,evidenceHash:h('evidence')};const sig=await witness.signTypedData(domain,wt,message);await expect(c.getFunction('witness')(eid,1,message.evidenceHash,sig)).revertedWith('NOT_INDEPENDENT');await expect(c.getFunction('witness')(h('unknown'),1,message.evidenceHash,sig)).revertedWith('UNKNOWN_EVENT');await expect(c.getFunction('witness')(eid,0,message.evidenceHash,sig)).revertedWith('INVALID_EVIDENCE');await expect(c.getFunction('approveWitness')(ethers.ZeroAddress,org)).revertedWith('EMPTY_ID');});
 it('anchors batches and verifies sorted-pair Merkle inclusion',async()=>{const{c}=await setup();const a=h('a'),b=h('b');const root=ethers.keccak256(ethers.concat([a,b].sort()));await c.getFunction('anchorBatch')(root,2,'ipfs://manifest');expect(await c.getFunction('verifyInclusion')(root,a,[b])).eq(true);expect(await c.getFunction('verifyInclusion')(root,h('wrong'),[b])).eq(false);await expect(c.getFunction('anchorBatch')(root,2,'')).revertedWith('DUPLICATE_BATCH');await expect(c.getFunction('anchorBatch')(zero,0,'')).revertedWith('INVALID_BATCH');});
 it('cannot initialize zero admin or set zero issuer',async()=>{await expect(ethers.deployContract('ModelLedgerRegistry',[ethers.ZeroAddress])).revertedWith('ZERO_ADMIN');const{c}=await setup();await expect(c.getFunction('setIssuer')(ethers.ZeroAddress)).revertedWith('EMPTY_ID');});
});
