import io

from PIL import Image


def image():
    out = io.BytesIO()
    Image.new("RGB", (60, 40), "#25a28a").save(out, format="PNG")
    return out.getvalue()


def test_unknown_upload_and_privacy(client, db):
    data = image()
    r = client.post("/api/v1/verify", files={"file": ("test.png", data, "image/png")})
    assert r.status_code == 200, r.text
    report = r.json()
    assert report["status"] == "UNVERIFIABLE"
    assert client.get("/api/v1/history").json() == []
    assert client.get("/api/v1/reports/" + report["report_id"]).status_code == 200
    certificate = client.get("/api/v1/reports/" + report["report_id"] + "/certificate").json()
    assert client.post("/api/v1/certificates/verify", json=certificate).json()["valid"]
    certificate["document"]["report"]["status"] = "VERIFIED"
    assert not client.post("/api/v1/certificates/verify", json=certificate).json()["valid"]
    pdf = client.get("/api/v1/reports/" + report["report_id"] + "/certificate?format=pdf")
    assert pdf.content.startswith(b"%PDF")


def test_registration_history_isolation(client):
    data = image()
    r = client.post(
        "/api/v1/register",
        files={"file": ("test.png", data)},
        data={"declared_origin": "User Model", "save_thumbnail": "true"},
    )
    assert r.status_code == 200, r.text
    version = r.json()["version"]
    assert version["thumbnail"].startswith("data:image/jpeg")
    r = client.post("/api/v1/verify", files={"file": ("test.png", data)}, data={"save_history": "true"})
    assert r.json()["origin_trust"] == "SELF_ASSERTED"
    assert len(client.get("/api/v1/history").json()) == 1
    report_id = r.json()["report_id"]
    client.cookies.clear()
    assert client.get("/api/v1/history").json() == []
    assert client.get("/api/v1/reports/" + report_id).status_code == 404
    assert client.get("/api/v1/audit/verify").json()["valid"]


def test_invalid_and_private_error(client):
    r = client.post("/api/v1/verify", files={"file": ("test.png", b"junk")})
    assert r.status_code == 422
    secret = "DO_NOT_LEAK_PRIVATE_PROMPT"
    r = client.post("/api/v1/events", json={"prompt": secret})
    assert r.status_code == 422 and secret not in r.text
    assert client.get("/api/v1/versions/missing").status_code == 404
    assert client.post("/api/v1/adversarial/run/not-real").status_code == 404
    assert client.get("/api/v1/health").json()["chain"]


def test_fake_embedded_metadata_is_never_upgraded(client):
    from PIL import PngImagePlugin

    meta = PngImagePlugin.PngInfo()
    meta.add_text("Software", "Generated by Model X")
    data = io.BytesIO()
    Image.new("RGB", (80, 40)).save(data, format="PNG", pnginfo=meta)
    report = client.post("/api/v1/verify", files={"file": ("fake.png", data.getvalue())}).json()
    assert report["origin_trust"] == "SELF_ASSERTED"
    assert report["status"] == "UNVERIFIABLE"
    assert "SELF_DECLARED_METADATA" in [r["code"] for r in report["reasons"]]


def test_signed_event_validation_does_not_echo_private_fields(client):
    import json

    secret = "PRIVATE_PROMPT_MUST_NOT_BE_IN_VALIDATION_ERRORS"
    response = client.post(
        "/api/v1/register",
        files={"file": ("image.png", image())},
        data={"signed_event": json.dumps({"prompt": secret})},
    )
    assert response.status_code == 422
    assert secret not in response.text
